Throw Exception if mandate is in pending state
mollie/laravel-cashier-mollie pull request #94
Opened 2022-06-13 07:53 UTC by ciungulete

2022-06-13 10:44 UTC, sandervanhooft requested changes
Nice first attempt.

2022-06-13 10:44 UTC, sandervanhooft commented on src/Exceptions/MandateIsNotYetFinalizedException.php
> +    public function __construct(string $message = 'The customer mandate is in pending', int $code = 404, Throwable $previous = null)
"... is still pending"

2022-06-13 10:44 UTC, sandervanhooft commented on tests/BaseTestCase.php
> +            'status' => 'pending',
Shouldn't this be mollie_mandate_status?

2022-06-15 06:43 UTC, ciungulete commented on tests/BaseTestCase.php
> +            'mollie_mandate_status' => 'pending',
We need it in `throwExceptionIfMandateIsInPendintState`

2022-06-21 13:57 UTC, sandervanhooft approved these changes

2022-06-21 13:57 UTC, merged